// Question bank mẫu. Mở rộng bằng cách thêm câu hỏi theo cùng cấu trúc.
// Đáp án và lời giải chỉ được dùng ở máy chủ, không gửi trong API lấy đề.
const questions = [
  // PHẦN I — NỀN TẢNG
  { id: 'F01', section: 'foundation', difficulty: 1, points: 1, topic: 'Đại số', skill: 'Phương trình bậc nhất', type: 'mcq', prompt: 'Giải phương trình 3x − 7 = 11.', choices: [{value:'4',label:'x = 4'},{value:'5',label:'x = 5'},{value:'6',label:'x = 6'},{value:'7',label:'x = 7'}], answer: '6', explanation: 'Cộng 7 hai vế được 3x = 18, chia 3 suy ra x = 6.', errorType: 'Biến đổi phương trình' },
  { id: 'F02', section: 'foundation', difficulty: 1, points: 1, topic: 'Số học', skill: 'Tỉ lệ phần trăm', type: 'mcq', prompt: '20% của 250 bằng bao nhiêu?', choices: [{value:'25',label:'25'},{value:'40',label:'40'},{value:'50',label:'50'},{value:'75',label:'75'}], answer: '50', explanation: '20% = 0,2 nên 0,2 × 250 = 50.', errorType: 'Chuyển đổi phần trăm' },
  { id: 'F03', section: 'foundation', difficulty: 1, points: 1, topic: 'Số học', skill: 'Căn bậc hai', type: 'short', prompt: 'Tính căn bậc hai số học của 144. Chỉ nhập kết quả.', answer: '12', accepted: ['12'], explanation: 'Vì 12² = 144 và căn bậc hai số học không âm nên kết quả là 12.', errorType: 'Kiến thức nền' },
  { id: 'F04', section: 'foundation', difficulty: 1, points: 1, topic: 'Lũy thừa', skill: 'Quy tắc lũy thừa', type: 'mcq', prompt: 'Rút gọn 2³ × 2⁴.', choices: [{value:'32',label:'2⁷ = 32'},{value:'64',label:'2⁶ = 64'},{value:'128',label:'2⁷ = 128'},{value:'256',label:'2⁸ = 256'}], answer: '128', explanation: 'Cùng cơ số thì cộng số mũ: 2³ × 2⁴ = 2⁷ = 128.', errorType: 'Quy tắc lũy thừa' },
  { id: 'F05', section: 'foundation', difficulty: 1, points: 1, topic: 'Đại số', skill: 'Hằng đẳng thức', type: 'mcq', prompt: 'Phân tích x² − 9 thành nhân tử.', choices: [{value:'a',label:'(x − 9)(x + 1)'},{value:'b',label:'(x − 3)(x + 3)'},{value:'c',label:'(x − 3)²'},{value:'d',label:'x(x − 9)'}], answer: 'b', explanation: 'Dùng hiệu hai bình phương: a² − b² = (a − b)(a + b).', errorType: 'Nhận dạng hằng đẳng thức' },
  { id: 'F06', section: 'foundation', difficulty: 1, points: 1, topic: 'Số học', skill: 'Tỉ số', type: 'short', prompt: 'Hai số có tỉ số 3 : 5 và tổng bằng 32. Số nhỏ là bao nhiêu?', answer: '12', accepted: ['12'], explanation: 'Tổng số phần là 3 + 5 = 8; mỗi phần bằng 32/8 = 4. Số nhỏ là 3 × 4 = 12.', errorType: 'Lập mô hình tỉ lệ' },
  { id: 'F07', section: 'foundation', difficulty: 1, points: 1, topic: 'Thống kê', skill: 'Trung vị', type: 'mcq', prompt: 'Trung vị của dãy 3; 5; 8; 10; 14 là số nào?', choices: [{value:'5',label:'5'},{value:'8',label:'8'},{value:'9',label:'9'},{value:'10',label:'10'}], answer: '8', explanation: 'Dãy có 5 số đã sắp xếp tăng dần, trung vị là số ở vị trí thứ 3.', errorType: 'Đọc dữ liệu' },
  { id: 'F08', section: 'foundation', difficulty: 1, points: 1, topic: 'Hình học', skill: 'Công thức hình học', type: 'match', prompt: 'Ghép mỗi đại lượng với công thức đúng.', pairs: [{prompt:'Diện tích hình tròn bán kính r', options:['πr²','2πr','πd'], key:'0'},{prompt:'Chu vi hình tròn bán kính r', options:['πr²','2πr','πr'], key:'1'},{prompt:'Chu vi hình tròn đường kính d', options:['πd','2πd','πd²'], key:'0'}], answer: {'0':'πr²','1':'2πr','2':'πd'}, explanation: 'Diện tích là πr²; chu vi theo bán kính là 2πr; chu vi theo đường kính là πd.', errorType: 'Nhầm lẫn công thức' },

  // PHẦN II — VẬN DỤNG
  { id: 'A01', section: 'application', difficulty: 2, points: 2, topic: 'Đại số', skill: 'Phương trình bậc hai', type: 'mcq', prompt: 'Hai nghiệm của phương trình x² − 5x + 6 = 0 là cặp nào?', choices: [{value:'a',label:'1 và 6'},{value:'b',label:'2 và 3'},{value:'c',label:'−2 và −3'},{value:'d',label:'−1 và −6'}], answer: 'b', explanation: 'x² − 5x + 6 = (x − 2)(x − 3), do đó x = 2 hoặc x = 3.', errorType: 'Phân tích phương trình' },
  { id: 'A02', section: 'application', difficulty: 2, points: 2, topic: 'Hàm số', skill: 'Giá trị hàm số', type: 'short', prompt: 'Cho f(x) = 2x² − 3. Tính f(−2).', answer: '5', accepted: ['5'], explanation: 'f(−2) = 2 × (−2)² − 3 = 8 − 3 = 5.', errorType: 'Thay giá trị vào hàm số' },
  { id: 'A03', section: 'application', difficulty: 2, points: 2, topic: 'Hình học', skill: 'Định lý Pythagore', type: 'mcq', prompt: 'Tam giác vuông có hai cạnh góc vuông dài 6 cm và 8 cm. Cạnh huyền dài bao nhiêu?', choices: [{value:'a',label:'9 cm'},{value:'b',label:'10 cm'},{value:'c',label:'12 cm'},{value:'d',label:'14 cm'}], answer: 'b', explanation: 'Theo Pythagore, c² = 6² + 8² = 100 nên c = 10 cm.', errorType: 'Chọn công thức hình học' },
  { id: 'A04', section: 'application', difficulty: 2, points: 2, topic: 'Xác suất', skill: 'Xác suất cơ bản', type: 'mcq', prompt: 'Một hộp có 3 viên bi đỏ và 2 viên bi xanh giống nhau về kích thước. Lấy ngẫu nhiên 1 viên. Xác suất lấy được bi đỏ là bao nhiêu?', choices: [{value:'a',label:'2/5'},{value:'b',label:'1/2'},{value:'c',label:'3/5'},{value:'d',label:'3/2'}], answer: 'c', explanation: 'Có 5 kết quả đồng khả năng và 3 kết quả thuận lợi, xác suất là 3/5.', errorType: 'Xác định không gian mẫu' },
  { id: 'A05', section: 'application', difficulty: 2, points: 2, topic: 'Đại số', skill: 'Hệ phương trình', type: 'mcq', prompt: 'Nghiệm (x, y) của hệ x + y = 7; x − y = 1 là gì?', choices: [{value:'a',label:'(3; 4)'},{value:'b',label:'(4; 3)'},{value:'c',label:'(5; 2)'},{value:'d',label:'(2; 5)'}], answer: 'b', explanation: 'Cộng hai phương trình được 2x = 8 nên x = 4; thay vào x + y = 7 suy ra y = 3.', errorType: 'Giải hệ phương trình' },
  { id: 'A06', section: 'application', difficulty: 2, points: 2, topic: 'Hàm số', skill: 'Hệ số góc', type: 'short', prompt: 'Đường thẳng đi qua A(1; 2) và B(3; 6). Hệ số góc của đường thẳng là bao nhiêu?', answer: '2', accepted: ['2'], explanation: 'Hệ số góc m = (6 − 2)/(3 − 1) = 4/2 = 2.', errorType: 'Đọc tọa độ' },
  { id: 'A07', section: 'application', difficulty: 2, points: 2, topic: 'Hàm số', skill: 'Nghiệm phương trình', type: 'mcq', prompt: 'Phương trình x² − 4x + 3 = 0 có nghiệm nào?', choices: [{value:'a',label:'x = 1 hoặc x = 3'},{value:'b',label:'x = −1 hoặc x = −3'},{value:'c',label:'x = 2 duy nhất'},{value:'d',label:'Vô nghiệm'}], answer: 'a', explanation: 'Phân tích x² − 4x + 3 = (x − 1)(x − 3).', errorType: 'Phân tích phương trình' },
  { id: 'A08', section: 'application', difficulty: 2, points: 2, topic: 'Hình học', skill: 'Tam giác đồng dạng', type: 'mcq', prompt: 'Hai tam giác đồng dạng có tỉ số độ dài tương ứng là 2. Tỉ số diện tích của chúng là bao nhiêu?', choices: [{value:'a',label:'2'},{value:'b',label:'3'},{value:'c',label:'4'},{value:'d',label:'8'}], answer: 'c', explanation: 'Tỉ số diện tích bằng bình phương tỉ số đồng dạng: 2² = 4.', errorType: 'Quan hệ tỉ số hình học' },

  // PHẦN III — THỬ THÁCH
  { id: 'C01', section: 'challenge', difficulty: 3, points: 3, topic: 'Xác suất', skill: 'Biến cố', type: 'mcq', prompt: 'Tung đồng thời hai đồng xu cân đối. Xác suất xuất hiện đúng một mặt ngửa là bao nhiêu?', choices: [{value:'a',label:'1/4'},{value:'b',label:'1/3'},{value:'c',label:'1/2'},{value:'d',label:'3/4'}], answer: 'c', explanation: 'Không gian mẫu gồm NN, NS, SN, SS. Có 2 trong 4 kết quả cho đúng một mặt ngửa nên xác suất là 1/2.', errorType: 'Đặt biến cố' },
  { id: 'C02', section: 'challenge', difficulty: 3, points: 3, topic: 'Tổ hợp', skill: 'Quy tắc đếm', type: 'short', prompt: 'Có 5 học sinh. Có bao nhiêu cách chọn 2 học sinh khác nhau để trực nhật, không phân biệt thứ tự?', answer: '10', accepted: ['10'], explanation: 'Số cách là C(5,2) = 5×4/(2×1) = 10.', errorType: 'Đếm trùng thứ tự' },
  { id: 'C03', section: 'challenge', difficulty: 3, points: 3, topic: 'Đại số', skill: 'Phương trình chứa dấu giá trị tuyệt đối', type: 'short', prompt: 'Giải |2x − 3| = 7. Nhập hai nghiệm theo thứ tự tăng dần, ngăn cách bằng dấu phẩy.', answer: '-2,5', accepted: ['-2,5','-2;5','-2 và 5','5,-2'], explanation: '2x − 3 = 7 cho x = 5; 2x − 3 = −7 cho x = −2. Hai nghiệm là −2 và 5.', errorType: 'Tách trường hợp' },
  { id: 'C04', section: 'challenge', difficulty: 3, points: 3, topic: 'Hàm số', skill: 'Giá trị nhỏ nhất của parabol', type: 'short', prompt: 'Giá trị nhỏ nhất của y = x² − 6x + 5 là bao nhiêu?', answer: '-4', accepted: ['-4'], explanation: 'y = (x − 3)² − 4 nên giá trị nhỏ nhất là −4.', errorType: 'Hoàn thành bình phương' },
  { id: 'C05', section: 'challenge', difficulty: 3, points: 3, topic: 'Hàm số', skill: 'Giao điểm hai đường thẳng', type: 'mcq', prompt: 'Giao điểm của y = 2x + 1 và y = −x + 7 là điểm nào?', choices: [{value:'a',label:'(1; 3)'},{value:'b',label:'(2; 5)'},{value:'c',label:'(3; 7)'},{value:'d',label:'(4; 9)'}], answer: 'b', explanation: 'Giải 2x + 1 = −x + 7 được x = 2; thay vào y = 5.', errorType: 'Kết hợp hai điều kiện' },
  { id: 'C06', section: 'challenge', difficulty: 3, points: 3, topic: 'Hình học', skill: 'Diện tích hình tròn', type: 'short', prompt: 'Một hình tròn có đường kính 10 cm. Diện tích bằng kπ cm². Tìm k.', answer: '25', accepted: ['25'], explanation: 'Bán kính r = 5 cm nên S = πr² = 25π cm², do đó k = 25.', errorType: 'Bán kính và đường kính' },
  { id: 'C07', section: 'challenge', difficulty: 3, points: 3, topic: 'Dãy số', skill: 'Cấp số cộng', type: 'short', prompt: 'Một cấp số cộng có ba số hạng đầu 4, 7, 10, ... Tìm số hạng thứ 10.', answer: '31', accepted: ['31'], explanation: 'Công sai d = 3; a₁₀ = 4 + 9×3 = 31.', errorType: 'Chỉ số số hạng' },
  { id: 'C08', section: 'challenge', difficulty: 3, points: 3, topic: 'Hàm số', skill: 'Vẽ đồ thị đường thẳng', type: 'graph', prompt: 'Trên hệ trục tọa độ, hãy đặt ít nhất hai điểm nằm trên đường thẳng y = 2x − 1. Bấm vào hệ trục để đặt điểm; có thể xóa điểm cuối.', graphBounds: {minX:-5,maxX:5,minY:-5,maxY:5}, graphFunction: {m:2,b:-1}, answer: 'graph-line', explanation: 'Một cách vẽ là chọn hai điểm (0; −1) và (1; 1), sau đó nối hai điểm để được đường thẳng y = 2x − 1.', errorType: 'Liên hệ tọa độ và đồ thị' },
  // BỔ SUNG — PHỦ RỘNG KIẾN THỨC (bộ câu hỏi nghiên cứu có thể mở rộng tiếp)
  { id: 'F09', section: 'foundation', difficulty: 1, points: 1, topic: 'Số học', skill: 'Ước chung lớn nhất', type: 'short', prompt: 'Tìm ƯCLN của 18 và 30.', answer: '6', accepted: ['6'], explanation: 'Các ước chung của 18 và 30 là 1, 2, 3, 6; số lớn nhất là 6.', errorType: 'Phân tích thừa số' },
  { id: 'F10', section: 'foundation', difficulty: 1, points: 1, topic: 'Số học', skill: 'Số nguyên', type: 'short', prompt: 'Tính −3 + 7.', answer: '4', accepted: ['4'], explanation: 'Hai số trái dấu nên lấy 7 − 3 = 4 và giữ dấu của số có giá trị tuyệt đối lớn hơn.', errorType: 'Quy tắc cộng số nguyên' },
  { id: 'F11', section: 'foundation', difficulty: 1, points: 1, topic: 'Đại số', skill: 'Phương trình bậc nhất', type: 'short', prompt: 'Tìm x biết 5x = 35.', answer: '7', accepted: ['7'], explanation: 'Chia hai vế cho 5 được x = 35/5 = 7.', errorType: 'Phép biến đổi tương đương' },
  { id: 'F12', section: 'foundation', difficulty: 1, points: 1, topic: 'Hàm số', skill: 'Giá trị hàm số', type: 'short', prompt: 'Cho y = 3x − 2. Tính y khi x = 4.', answer: '10', accepted: ['10'], explanation: 'Thay x = 4: y = 3 × 4 − 2 = 10.', errorType: 'Thay biến' },
  { id: 'F13', section: 'foundation', difficulty: 1, points: 1, topic: 'Hình học', skill: 'Tổng ba góc tam giác', type: 'short', prompt: 'Một tam giác có hai góc bằng 40° và 60°. Góc còn lại bằng bao nhiêu độ?', answer: '80', accepted: ['80','80 độ','80°'], explanation: 'Tổng ba góc trong một tam giác bằng 180°, nên góc còn lại bằng 180° − 40° − 60° = 80°.', errorType: 'Tổng góc tam giác' },
  { id: 'F14', section: 'foundation', difficulty: 1, points: 1, topic: 'Tỉ lệ phần trăm', skill: 'Phần trăm trong thực tế', type: 'short', prompt: 'Một món hàng giá 200.000 đồng được giảm 15%. Giá sau giảm là bao nhiêu đồng? Chỉ nhập số.', answer: '170000', accepted: ['170000','170.000'], explanation: 'Tiền giảm là 200.000 × 15% = 30.000 đồng; giá sau giảm là 170.000 đồng.', errorType: 'Tính phần trăm' },
  { id: 'F15', section: 'foundation', difficulty: 1, points: 1, topic: 'Xác suất', skill: 'Xác suất cơ bản', type: 'mcq', prompt: 'Chọn ngẫu nhiên một số nguyên từ 1 đến 8. Xác suất chọn được số chẵn là bao nhiêu?', choices: [{value:'1/4',label:'1/4'},{value:'1/2',label:'1/2'},{value:'3/4',label:'3/4'},{value:'1/8',label:'1/8'}], answer: '1/2', explanation: 'Có 4 số chẵn trong 8 số đồng khả năng nên xác suất là 4/8 = 1/2.', errorType: 'Đếm kết quả thuận lợi' },
  { id: 'F16', section: 'foundation', difficulty: 1, points: 1, topic: 'Đại số', skill: 'Thu gọn biểu thức', type: 'short', prompt: 'Thu gọn biểu thức 3(a + 2) − 2a.', answer: 'a+6', accepted: ['a+6','6+a'], explanation: 'Phân phối 3: 3a + 6 − 2a = a + 6.', errorType: 'Phân phối và gom hạng tử' },

  { id: 'A09', section: 'application', difficulty: 2, points: 2, topic: 'Đại số', skill: 'Hệ phương trình', type: 'short', prompt: 'Giải hệ x + y = 9; x − y = 3. Nhập x, y theo thứ tự, ngăn cách bằng dấu phẩy.', answer: '6,3', accepted: ['6,3','6;3','x=6,y=3','6 và 3'], explanation: 'Cộng hai phương trình được 2x = 12 nên x = 6. Thay vào x + y = 9 được y = 3.', errorType: 'Kết hợp phương trình' },
  { id: 'A10', section: 'application', difficulty: 2, points: 2, topic: 'Đại số', skill: 'Phương trình bậc hai', type: 'mcq', prompt: 'Nghiệm của phương trình x² − 9 = 0 là gì?', choices: [{value:'a',label:'x = 3'},{value:'b',label:'x = −3'},{value:'c',label:'x = −3 hoặc x = 3'},{value:'d',label:'Vô nghiệm'}], answer: 'c', explanation: 'x² = 9 nên x = ±3. Cần xét đủ hai nghiệm.', errorType: 'Bỏ sót nghiệm' },
  { id: 'A11', section: 'application', difficulty: 2, points: 2, topic: 'Hình học', skill: 'Chu vi hình tròn', type: 'short', prompt: 'Hình tròn có bán kính 4 cm. Chu vi bằng kπ cm. Tìm k.', answer: '8', accepted: ['8'], explanation: 'C = 2πr = 2π × 4 = 8π cm, nên k = 8.', errorType: 'Chọn công thức chu vi' },
  { id: 'A12', section: 'application', difficulty: 2, points: 2, topic: 'Thống kê', skill: 'Số trung bình', type: 'short', prompt: 'Tính số trung bình cộng của 3, 5, 7, 9.', answer: '6', accepted: ['6'], explanation: 'Trung bình cộng bằng (3 + 5 + 7 + 9)/4 = 24/4 = 6.', errorType: 'Chia cho số lượng dữ liệu' },
  { id: 'A13', section: 'application', difficulty: 2, points: 2, topic: 'Hàm số', skill: 'Hệ số góc', type: 'mcq', prompt: 'Đường thẳng y = −3x + 5 có hệ số góc bằng bao nhiêu?', choices: [{value:'a',label:'5'},{value:'b',label:'3'},{value:'c',label:'−3'},{value:'d',label:'−5'}], answer: 'c', explanation: 'Ở dạng y = ax + b, hệ số góc là hệ số a đứng trước x; ở đây a = −3.', errorType: 'Nhận diện hệ số góc' },
  { id: 'A14', section: 'application', difficulty: 2, points: 2, topic: 'Xác suất', skill: 'Không gian mẫu', type: 'mcq', prompt: 'Gieo một con xúc xắc cân đối. Xác suất xuất hiện số lớn hơn 4 là bao nhiêu?', choices: [{value:'a',label:'1/6'},{value:'b',label:'1/3'},{value:'c',label:'1/2'},{value:'d',label:'2/3'}], answer: 'b', explanation: 'Các kết quả thuận lợi là 5 và 6, có 2 trên 6 kết quả đồng khả năng; xác suất = 2/6 = 1/3.', errorType: 'Xác định kết quả thuận lợi' },
  { id: 'A15', section: 'application', difficulty: 2, points: 2, topic: 'Đại số', skill: 'Biệt thức delta', type: 'mcq', prompt: 'Biệt thức Δ của phương trình x² − 6x + 9 = 0 bằng bao nhiêu?', choices: [{value:'a',label:'−9'},{value:'b',label:'0'},{value:'c',label:'9'},{value:'d',label:'36'}], answer: 'b', explanation: 'a = 1, b = −6, c = 9 nên Δ = b² − 4ac = 36 − 36 = 0.', errorType: 'Thay hệ số vào biệt thức' },
  { id: 'A16', section: 'application', difficulty: 2, points: 2, topic: 'Hình học', skill: 'Tam giác đồng dạng', type: 'short', prompt: 'Hai tam giác đồng dạng có tỉ số đồng dạng 3. Tỉ số diện tích của chúng là bao nhiêu?', answer: '9', accepted: ['9'], explanation: 'Tỉ số diện tích bằng bình phương tỉ số đồng dạng: 3² = 9.', errorType: 'Bình phương tỉ số đồng dạng' },

  { id: 'C09', section: 'challenge', difficulty: 3, points: 3, topic: 'Xác suất', skill: 'Biến cố', type: 'mcq', prompt: 'Gieo đồng thời hai con xúc xắc cân đối. Xác suất để tổng số chấm bằng 7 là bao nhiêu?', choices: [{value:'a',label:'1/12'},{value:'b',label:'1/6'},{value:'c',label:'1/4'},{value:'d',label:'7/36'}], answer: 'b', explanation: 'Có 6 cặp có thứ tự cho tổng bằng 7 trong 36 kết quả đồng khả năng, nên xác suất là 6/36 = 1/6.', errorType: 'Liệt kê không gian mẫu' },
  { id: 'C10', section: 'challenge', difficulty: 3, points: 3, topic: 'Tổ hợp', skill: 'Quy tắc đếm', type: 'short', prompt: 'Từ 6 học sinh, có bao nhiêu cách chọn 3 bạn vào một nhóm nếu không phân biệt thứ tự?', answer: '20', accepted: ['20'], explanation: 'Số cách chọn là C(6,3) = 6!/(3!3!) = 20.', errorType: 'Tính tổ hợp' },
  { id: 'C11', section: 'challenge', difficulty: 3, points: 3, topic: 'Dãy số', skill: 'Cấp số cộng', type: 'short', prompt: 'Cấp số cộng 2, 5, 8, 11, ... có số hạng thứ 15 bằng bao nhiêu?', answer: '44', accepted: ['44'], explanation: 'a₁ = 2, d = 3 nên a₁₅ = a₁ + 14d = 2 + 42 = 44.', errorType: 'Đếm số bước công sai' },
  { id: 'C12', section: 'challenge', difficulty: 3, points: 3, topic: 'Hàm số', skill: 'Giá trị nhỏ nhất của parabol', type: 'short', prompt: 'Tìm giá trị nhỏ nhất của y = x² + 4x + 1.', answer: '-3', accepted: ['-3'], explanation: 'Hoàn thành bình phương: y = (x + 2)² − 3. Giá trị nhỏ nhất là −3.', errorType: 'Hoàn thành bình phương' },
  { id: 'C13', section: 'challenge', difficulty: 3, points: 3, topic: 'Đại số', skill: 'Phương trình chứa căn', type: 'short', prompt: 'Giải √(x + 1) = 3. Tìm x.', answer: '8', accepted: ['8'], explanation: 'Điều kiện x ≥ −1. Bình phương hai vế được x + 1 = 9, suy ra x = 8; nghiệm thỏa điều kiện.', errorType: 'Điều kiện và bình phương' },
  { id: 'C14', section: 'challenge', difficulty: 3, points: 3, topic: 'Hình học', skill: 'Định lý Pythagore', type: 'short', prompt: 'Tam giác vuông có hai cạnh góc vuông 9 cm và 12 cm. Tính cạnh huyền.', answer: '15', accepted: ['15'], explanation: 'Theo Pythagore: c² = 9² + 12² = 81 + 144 = 225 nên c = 15 cm.', errorType: 'Căn bậc hai khi dùng Pythagore' },
  { id: 'C15', section: 'challenge', difficulty: 3, points: 3, topic: 'Đại số', skill: 'Phân thức đại số', type: 'mcq', prompt: 'Với x ≠ 0, rút gọn (x² − 4)/x có kết quả nào?', choices: [{value:'a',label:'x − 4'},{value:'b',label:'x − 4/x'},{value:'c',label:'x² − 4x'},{value:'d',label:'x + 2'}], answer: 'b', explanation: '(x² − 4)/x = x²/x − 4/x = x − 4/x, với điều kiện x ≠ 0.', errorType: 'Chia từng hạng tử cho mẫu' },
  { id: 'C16', section: 'challenge', difficulty: 3, points: 3, topic: 'Hàm số', skill: 'Giao điểm hai đường thẳng', type: 'short', prompt: 'Tìm hoành độ giao điểm của y = 3x − 2 và y = x + 4.', answer: '3', accepted: ['3'], explanation: 'Tại giao điểm: 3x − 2 = x + 4, suy ra 2x = 6 và x = 3.', errorType: 'Lập phương trình hoành độ giao điểm' },
];

const SECTION_LABELS = { foundation: 'Phần I · Nền tảng', application: 'Phần II · Vận dụng', challenge: 'Phần III · Thử thách' };

function publicQuestion(q) {
  const out = {
    id: q.id, section: q.section, sectionLabel: SECTION_LABELS[q.section], difficulty: q.difficulty,
    points: q.points, topic: q.topic, skill: q.skill, type: q.type, prompt: q.prompt
  };
  if (q.choices) out.choices = q.choices;
  if (q.pairs) out.pairs = q.pairs.map(p => ({prompt:p.prompt, options:p.options}));
  if (q.graphBounds) out.graphBounds = q.graphBounds;
  return out;
}

module.exports = { questions, publicQuestion, SECTION_LABELS };
